---
name: 'build dev images'

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

permissions: write-all

jobs:
  build-images:
    uses: ./.github/workflows/build_docker_images.yml
    with:
      image-tag: dev
      version-tag: ${{ github.ref_name }}
      use-cache: true
    secrets: inherit
